services:
  db:
    image: postgres:16-alpine
    container_name: postgres_cars_catalog
    environment:
      POSTGRES_DB: cars_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cars_catalog"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      args:
        INSTALL_DEV: "false"
    container_name: app_cars_catalog
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: