[project]
name = "fastapi-example-cars-catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.135.1",
    "passlib[bcrypt]>=1.7.4",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2.0.48",
]

[dependency-groups]
dev = [
    "ruff>=0.15.9",
]

[tool.ruff]
exclude = [
    ".venv",
    ".vscode",
    "temp_*",
    "test_*"
]
src = ["src"]
line-length = 150
target-version = "py312"

[tool.ruff.lint]
select = ["E","F","UP","B","SIM","I","W"]
ignore = ["E712", "B008"]
